# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        
      - name: Show Python Version  
        run: python --version
      
      - name: Install Mkdocs
        run: pip install mkdocs
        
      - name: Install Material Theme
        run: pip install mkdocs-material
        
      - name: Build Docs
        run: mkdocs build
        
      - name: zip out
        run: |
             zip -r SensingPlatform.zip site/*
             ls
           
      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          # 填写Bucket所在地域的域名信息，可参考访问域名和数据中心。
          endpoint: oss-cn-shanghai.aliyuncs.com	
          # AccessKey ID
          access-key-id: ${{secrets.ACCESSKEYID}}
          # AccessKeySceret
          access-key-secret:  ${{secrets.ACCESSKEYSECRET}}
      - run: ossutil cp -rf SensingPlatform.zip oss://troncell-docs/zips/
      
      
          
      
